services:

  demo-api:
    image: demo-api
    build:
      context: ./demoapi
      dockerfile: Dockerfile
    ports:
      - "5101:8080"

  demo-app:
    image: demo-app
    build:
      context: ./demoapp
      dockerfile: Dockerfile
    ports:
      - "5102:8080"
    depends_on:
      - demo-api
    environment:
      - API_URL=http://host.docker.internal:5101/weatherforecast